import type { Metadata } from "next";
import { ThemeProvider } from "@/src/components/theme-provider"
import "./globals.css";
import Header from "@/src/components/layout/global/header";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="fr" suppressHydrationWarning> 
            <body className="antialiased min-h-screen flex flex-col">
                <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                    <Header />
                        <main className="flex-1 min-h-[calc(100vh-4rem)]"> 
                            {children}
                        </main>
                </ThemeProvider>
            </body>
        </html>
    )
}

